FROM mhart/alpine-node
FROM mhart/alpine-node

# Create app directory
RUN mkdir -p /usr/src/app && echo "Oxygen Webapp"
COPY package.json /usr/src/app/
WORKDIR /usr/src/app
RUN npm install --production
COPY . /usr/src/app/

EXPOSE 8080

WORKDIR /usr/src/app
CMD ["npm", "start"]